import { StyleSheet } from 'react-native';

import { fonts, type ThemePalette } from '../theme';

export const createWorkspacePickerStyles = (colors: ThemePalette) =>
  StyleSheet.create({
    overlay: { flex: 1 },
    backdrop: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: colors.scrim,
    },
    keyboardAvoider: { flex: 1, justifyContent: 'flex-end' },
    cardAnchor: { flexShrink: 1 },
    sheet: {
      flexGrow: 0,
      flexShrink: 1,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.line,
    },
    sheetContent: {
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 16,
    },
    title: {
      color: colors.text,
      fontSize: 17,
      fontWeight: '800',
      marginBottom: 6,
    },
    hint: {
      color: colors.muted,
      fontSize: 12,
      lineHeight: 17,
      marginBottom: 8,
    },
    notice: {
      color: colors.danger,
      fontSize: 12,
      lineHeight: 16,
      marginBottom: 6,
    },
    listContent: { paddingVertical: 4 },
    loading: {
      minHeight: 72,
      alignItems: 'center',
      justifyContent: 'center',
    },
    empty: {
      color: colors.muted,
      fontSize: 13,
      textAlign: 'center',
      paddingVertical: 24,
    },
    rowShell: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.line,
    },
    row: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
      paddingRight: 2,
    },
    rowSelect: {
      flex: 1,
      minHeight: 42,
      flexDirection: 'row',
      alignItems: 'center',
    },
    rowActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginLeft: 8,
    },
    disabledRow: { opacity: 0.56 },
    rowCopy: { flex: 1 },
    rowTitle: { color: colors.text, fontSize: 15, fontWeight: '700' },
    rowStatus: {
      color: colors.muted,
      fontSize: 11,
      fontFamily: fonts.mono,
      marginTop: 2,
    },
    check: {
      width: 24,
      alignItems: 'flex-start',
      marginRight: 8,
    },
    forgetButton: {
      borderRadius: 13,
      backgroundColor: colors.surfaceRaised,
      paddingHorizontal: 10,
      paddingVertical: 6,
      marginLeft: 8,
    },
    forgetText: { color: colors.textDim, fontSize: 11, fontWeight: '700' },
    selectionPrompt: {
      borderRadius: 14,
      backgroundColor: colors.surfaceRaised,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginBottom: 8,
    },
    selectionPromptText: {
      color: colors.text,
      fontSize: 12,
      fontWeight: '700',
      marginBottom: 8,
    },
    selectionPromptActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    newRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 8,
    },
    input: {
      flex: 1,
      minHeight: 38,
      borderRadius: 19,
      backgroundColor: colors.surfaceRaised,
      color: colors.text,
      fontSize: 14,
      paddingHorizontal: 13,
    },
    actionChip: {
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.surfaceRaised,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 12,
    },
    actionDisabled: { opacity: 0.5 },
    actionText: { color: colors.textDim, fontSize: 12, fontWeight: '700' },
    footerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 16,
      marginTop: 10,
    },
    footerAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      minHeight: 36,
    },
    footerActionText: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
    },
    pressed: { opacity: 0.58 },
  });
